# Config file for automatic testing at travis-ci.org

language: python

matrix:
    include:
        -   python: 3.7
            env: TOXENV=py37
        -   python: 3.8
            env: TOXENV=py38
        -   python: 3.9
            env: TOXENV=py39
        -   python: 3.7
            env: TOXENV=py3pep8
        -   python: 3.7
            env: TOXENV=docs

# command to install dependencies for getting Tox running, other dependecies are installed by Tox
before_install:
    - pip install codecov tox

# command to run tests, e.g. python setup.py test
script:
    - tox

after_success:
    - codecov -e TOXENV
