# Config file for automatic testing at travis-ci.org

language: python

matrix:
    include:
        -   python: 3.7
            env: TOXENV=py37
        -   python: 3.8
            env: TOXENV=py38
        -   python: 3.9
            env: TOXENV=py39
        -   python: 3.7
            env: TOXENV=py3pep8
        -   python: 3.7
            env: TOXENV=docs

# command to install dependencies for getting Tox running, other dependecies are installed by Tox
before_install:
    - pip install codecov tox

# command to run tests, e.g. python setup.py test
script:
    - tox

after_success:
    - codecov -e TOXENV

deploy:
  provider: pypi
  username: __token__
  password:
    secure: WH1BdHPUPuFdQLCsLl9si8NveW8d7bAccITrrIjW9irMBfGsUlHCfX+PD2+SgftUC9yZiUroxBdimXnPn7K3CfPTWAOeQHEL5NyjdJyvzDyYSS87Cg//JCqHczc5Re+gXO9iHl3gc/21TcViQmXUVOTWJSSEGa2AWOXF+t6Ys5qdxla5YWpKR2pBtVmDuVvMKpjrf5emmTSjRhnzChExm071F0SLftcK/pdITpAsgmhYyBtCvda8vFxAlPYblOfQTxDPA6lvNAYTg51fPQkHP7wL+rkek7uS9x7gpHaOPkXrCL1IY9onQNi8lFCKhoVbwgQG2YaUlGktf72yEg5YHuZrKoakRuHiH8TzOW/wZkKNmBOuN5Rr3uNu8Xm28ibuq4KkBkrUOeiyMQCmkQmTDEzr2g4Csva7Qg8gOZDOISdzkxjofil6Slq0W2s08NA8emzLzlW9vXt4HHmfqHjrbnUlVYpy6ujV7qE/ZgpTrNQ22+QGL8dKbBRYcr7JmpRwe3oGdJs6vb9dPi/vDb+2cBYkr5N95ByM1UTxKjaVF//hXkPQGl9jfWZJwmteNuJLhixcUepr9OIgKVSZGJRNWdaFk5FBGl8v6raYQ+d5j+EgQiB6r0AaYCKdenUsOXBFPaQfeMFuHY/sansZedrM6eLNMDZClYqa10a4QNDSrHc=
  skip_existing: true
  distributions: sdist bdist_wheel
  on:
    condition: $TOXENV == py37
    tags: true
